// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ObjectID defines model for ObjectID.
type ObjectID struct {
	Id string `json:"id"`
}

// Problem RFC 9457 Problem Details
type Problem struct {
	Detail     *string            `json:"detail,omitempty"`
	Instance   *string            `json:"instance,omitempty"`
	Parameters *map[string]string `json:"parameters,omitempty"`
	Status     *int               `json:"status,omitempty"`
	Title      *string            `json:"title,omitempty"`
	Type       *string            `json:"type,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Delete an object
	// (DELETE /objects/{bucket}/{objectId})
	DeleteObject(c *gin.Context, bucket string, objectId string)
	// Download an object
	// (GET /objects/{bucket}/{objectId})
	DownloadObject(c *gin.Context, bucket string, objectId string)
	// Upload or replace an object
	// (PUT /objects/{bucket}/{objectId})
	UploadObject(c *gin.Context, bucket string, objectId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// DeleteObject operation middleware
func (siw *ServerInterfaceWrapper) DeleteObject(c *gin.Context) {

	var err error

	// ------------- Path parameter "bucket" -------------
	var bucket string

	err = runtime.BindStyledParameterWithOptions("simple", "bucket", c.Param("bucket"), &bucket, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter bucket: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "objectId" -------------
	var objectId string

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteObject(c, bucket, objectId)
}

// DownloadObject operation middleware
func (siw *ServerInterfaceWrapper) DownloadObject(c *gin.Context) {

	var err error

	// ------------- Path parameter "bucket" -------------
	var bucket string

	err = runtime.BindStyledParameterWithOptions("simple", "bucket", c.Param("bucket"), &bucket, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter bucket: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "objectId" -------------
	var objectId string

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DownloadObject(c, bucket, objectId)
}

// UploadObject operation middleware
func (siw *ServerInterfaceWrapper) UploadObject(c *gin.Context) {

	var err error

	// ------------- Path parameter "bucket" -------------
	var bucket string

	err = runtime.BindStyledParameterWithOptions("simple", "bucket", c.Param("bucket"), &bucket, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter bucket: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "objectId" -------------
	var objectId string

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UploadObject(c, bucket, objectId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.DELETE(options.BaseURL+"/objects/:bucket/:objectId", wrapper.DeleteObject)
	router.GET(options.BaseURL+"/objects/:bucket/:objectId", wrapper.DownloadObject)
	router.PUT(options.BaseURL+"/objects/:bucket/:objectId", wrapper.UploadObject)
}
